### ISSUE TITLE
Trim whitespace before/after comma in multiple: true fields

### ISSUE THREAD

**Issue by timhutchens** [aklajnert/changelogd#23]
* changelogd version: 0.1.5
* Python version: 3.10.6
* Operating System: Mac OS

### Description

When I add multiple entries to an entry for a field with `multiple: true`, if I put a space after the comma, the value for the second entry (and subsequent entries) end up being single quoted with a leading space in the entry.yaml file. Since this happens while producing the entry.yaml file, trimming the whitespace in the entry.md template doesn't help. So I'd need a config option or just have it trim the whitespace before/after the comma separated values by default. 

### What I Did

```
# entry
changelogd entry

Select message type [1]: 1
Merge Request (number only) (required): 1
Messages (separate multiple values with comma): string1, string2
Created changelog entry at /pathToRepo/changelog.d/other.56871af2.entry.yaml

# entry.yaml output example
merge_request: '1'
messages:
- string1
- ' string2'
timestamp: 1663063391
type: other
```

**Comment by aklajnert** [comment]
Thanks for reporting. I'll look at it deeper somewhere around the next month, as I'm a bit overwhelmed by other stuff right now. Just out of curiosity - why do you use multiple value fields for messages? What is your use case here?

**Comment by timhutchens** [comment]
We took the fairly open-ended engine you built and modified the config so that the Type of entry was the top level heading, followed by MRs (merge requests), then used the multiple message fields to create a bullet list under that. This produced a more meaningful/readable changelog for the repo we're working on.  

![image](https://user-images.githubusercontent.com/45564702/189900497-d20629d6-1a1e-4275-8673-96bf3a91b1dc.png)

**Comment by aklajnert** [comment]
Oh, that looks nice - thanks for showing me that example. As I mentioned earlier, I'll work on it next month. If you want it earlier, feel free to submit a PR for it.

**Comment by aklajnert** [comment]
@timhutchens - this is now resolved on master. Would you like to test it first, or should I release a new version?

**Comment by timhutchens** [comment]
I'm comfortable with you just cutting a new release/version based on the changes.

**Comment by aklajnert** [comment]
Ok, just released a new version.

**Comment by timhutchens** [comment]
Thank you! Confirmed working and passed the word on to my team to pick up the new version.
